### ISSUE TITLE
Flickering buttons

### ISSUE THREAD

**Issue by krizf** [xx450/jTime#2]
From time to time, the order of the buttons seems to change a for a fraction of a second, which causes a disturbing "flickering" effect. If the button in question is "active one" it is noticable

**Comment by xx450** [comment]
@krizf do you remember exact steps that you did prior this issue has occurred? I'm unable to reproduce it.

**Comment by xx450** [comment]
please remind if you still experience "the flickering" issue..

**Comment by xx450** [comment]
I have not experienced any issue with this for a long time.... so closing
